name: Deploy
on:
    push:
        branches:
            - main

jobs:
    deploy-site:
        runs-on: ubuntu-latest
        name: Deploy Site
        steps:
            - uses: actions/checkout@v4

            - name: Install node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-2

            - name: Deploy static site
              run: yarn deploy
